load("@package_metadata//licenses:defs.bzl", package_metadata_license = "license")
load("@package_metadata//purl:purl.bzl", "purl")
load("@package_metadata//rules:package_metadata.bzl", "package_metadata")
load("@rules_license//rules:license.bzl", "license")

package(
    default_applicable_licenses = [":license"],
    default_visibility = ["//visibility:public"],
)

license(
    name = "license",
    copyright_notice = "Copyright 2025-2026 Rilla Network; portions Copyright Yann Degat and The Bazel Authors. See NOTICE.",
    license_kinds = [
        "@rules_license//licenses/spdx:Apache-2.0",
    ],
    license_text = "LICENSE",
    package_name = "rules_tf",
)

package_metadata(
    name = "package_metadata",
    attributes = [
        ":package_metadata_license",
    ],
    purl = purl.bazel(
        module_name(),
        module_version(),
    ),
)

package_metadata_license(
    name = "package_metadata_license",
    kind = "@package_metadata//licenses/spdx:Apache-2.0",
)

toolchain_type(
    name = "tflint_toolchain_type",
    visibility = ["//visibility:public"],
)

toolchain_type(
    name = "tf_toolchain_type",
    visibility = ["//visibility:public"],
)

toolchain_type(
    name = "tfdoc_toolchain_type",
    visibility = ["//visibility:public"],
)
