load("@rules_tf//tf:def.bzl", "tf_module")

tf_module(
    name = "root-mod-a",
    backend = {
        "local": {
            "path": "terraform.tfstate",
        },
    },
    providers = {
        "random": "hashicorp/random:3.3.2",
        "terraform": "terraform.io/builtin/terraform",
    },
    root = True,
    tf_version = ">= 1.9, <= 1.10",
    tflint_config = "//tf:tflint-custom-config",
    tfvars = {
        "input_var": "from-bazel-tfvars",
        "regions": [
            "ap-southeast-1",
            "ap-south-1",
        ],
        "enabled": True,
        "replica_count": 3,
        "labels": {"team": "platform"},
    },
    deps = [
        "//tf/modules/mod-a",
    ],
)
