"""Rendering a module's `.terraform.lock.hcl` from the mirror's resolved coordinates.

A module initialised against an unpacked mirror (`init -plugin-dir=...`) has no
lock file to read, so terraform hashes the packages it finds, writes what it
computed, and warns that the result covers only the platform it ran on. Every
one of those hashes is already known here: the module extension resolved a
signature-checked sha256 for every platform before a byte was fetched, and Bazel
fetched each package against one. Writing those hashes into the module's rundir
states what was mirrored, and the warning goes with it.

Two schemes go in, because terraform reads them in different places. A `zh:`
value is the sha256 of a release zip, which is what the extension verified
against the publisher's signature and what Bazel fetched against -- but a mirror
hands terraform an extracted directory, which it can only hash as `h1:`, so the
`zh:` entries are ones terraform takes as given. The `h1:` values are the ones
it can actually check, and are why the document is left alone by `init` instead
of being rewritten with whatever the running platform computed.

Which makes the document a record first and a constraint second: the check that
matters already ran in the extension, and terraform's own check at `init` is a
second line covering the tree after Bazel unpacked it.

The one field that is not set-shaped is `version`: a lock file holds one per
provider address, two blocks for one address is a hard `Duplicate provider lock`
error, and a version outside a module's constraints fails `init` outright. So
when the mirror stocks a source at several versions, the module's own declared
constraint picks between them, exactly as terraform's own selection would.
"""

load(":provider_mirror.bzl", "provider_source_parts")
load(":semver.bzl", "select_matching_version")

_HEADER = """# Generated by rules_tf from the provider mirror. Do not edit.
#
# The zh: hashes below are the package sha256s the module extension resolved
# when the mirror was built, one per platform; the h1: hashes cover the same
# packages extracted, as terraform installs them. The mirror is the only place
# these providers can be installed from, so this records what terraform is about
# to link rather than constraining what it may choose.
"""

_PROVIDER_BLOCK = """
provider "{address}" {{
  version = "{version}"
  hashes = [
{hashes}
  ]
}}
"""

def parse_mirror_hashes(mirror_hashes):
    """Regroups the toolchain's flat hash table by provider address.

    Args:
      mirror_hashes: {"<host>/<ns>/<type>@<version>": "<hash>,<hash>,..."}, as
        the tf toolchain carries it; each hash scheme-prefixed ("zh:" or "h1:")
        as a lock document spells it.

    Returns:
      {"<host>/<ns>/<type>": {"<version>": ["<hash>", ...]}}.
    """
    by_address = {}
    for key, joined in mirror_hashes.items():
        address, _, version = key.rpartition("@")
        by_address.setdefault(address, {})[version] = [h for h in joined.split(",") if h]

    return by_address

def declared_constraints(declared, default_registry):
    """Collects the providers a module tree declares, and the constraints on each.

    Every declared address gets an entry, including one declared without a
    version: presence is what says the module requires the provider at all,
    which decides whether the lock file may name it, while the constraints
    decide which version it names.

    Args:
      declared: the `providers` dicts of a module and everything it depends on,
        each {alias: {"source": ..., "version": ...}}, as `tf_module` normalises
        them.
      default_registry: registry host an unqualified source resolves against.

    Returns:
      {"<host>/<ns>/<type>": ["<constraint>", ...]}, the list empty for an
      address declared with no version.
    """
    constraints = {}
    for providers in declared:
        for config in providers.values():
            host, namespace, provider_type = provider_source_parts(
                config["source"],
                default_registry,
            )
            address = "%s/%s/%s" % (host, namespace, provider_type)
            specs = constraints.setdefault(address, [])

            spec = config.get("version")
            if spec and spec not in specs:
                specs.append(spec)

    return constraints

def _satisfying_version(versions, specs):
    """The version a module's declared constraints select, or "".

    Args:
      versions: the versions the mirror stocks for one address.
      specs: the constraints declared for it.

    Returns:
      The highest satisfying version, or "" when none satisfies.
    """

    # Comma-joined is terraform's own spelling of AND, and what
    # `parse_version_constraint` reads.
    version = select_matching_version(versions, ", ".join(specs))
    if version:
        return version

    # A prerelease is never selected by a constraint, in terraform or in the
    # solver above -- naming one takes an exact pin, so an exact pin is what is
    # looked for here.
    pins = [
        spec.strip()[1:].strip() if spec.strip().startswith("=") else spec.strip()
        for spec in specs
    ]
    for candidate in versions:
        if candidate in pins:
            return candidate

    return ""

def select_lock_versions(by_address, constraints):
    """Chooses the one version per provider address that the lock file names.

    Only providers the module tree declares are named. A mirror is shared across
    every module in a workspace, so it stocks providers any one module has
    nothing to do with -- and `init` prunes a block the configuration does not
    require, rewriting the file to do it. That rewrite is the whole of what the
    generated document exists to avoid, so a source nothing declared is left
    out even when the mirror stocks it exactly once.

    A declared address carrying no constraint is named when the mirror stocks it
    once: with nothing to choose between versions, one stocked version is the
    only thing `init` could install. Everything else is decided by the declared
    constraints, ANDed together the way terraform ANDs them across a
    configuration.

    An address whose constraints select none of the mirrored versions is left
    out, whether the mirror stocks one version or several. Both the lock file
    and the configuration would be unsatisfiable, but only the unlocked failure
    names the real problem: terraform reports that no release matches, rather
    than that the lock file disagrees with the configuration.

    Args:
      by_address: mirror contents, as `parse_mirror_hashes` returns them.
      constraints: declared providers, as `declared_constraints` returns them.

    Returns:
      {"<host>/<ns>/<type>": "<version>"}, covering the addresses that can be
      named.
    """
    selected = {}
    for address, versions in by_address.items():
        specs = constraints.get(address)
        if specs == None:
            continue

        if not specs:
            if len(versions) == 1:
                selected[address] = versions.keys()[0]
            continue

        version = _satisfying_version(versions.keys(), specs)
        if version:
            selected[address] = version

    return selected

def render_lock_document(by_address, selected):
    """Renders the `.terraform.lock.hcl` document for the selected versions.

    Every platform's hash goes into the block, since `hashes` is a set that
    terraform matches the installed package against: the members covering other
    platforms are what let one document serve every machine in a team. The
    hashes arrive already carrying their scheme, so both are emitted as they
    were given -- sorted, which happens to put `h1:` ahead of `zh:` the way
    terraform writes them itself.

    Args:
      by_address: mirror contents, as `parse_mirror_hashes` returns them.
      selected: one version per address, as `select_lock_versions` returns.

    Returns:
      The document, or "" when no provider could be named in one.
    """
    if not selected:
        return ""

    blocks = []
    for address in sorted(selected):
        version = selected[address]
        hashes = sorted(by_address[address][version])
        blocks.append(_PROVIDER_BLOCK.format(
            address = address,
            version = version,
            hashes = ",\n".join(["    \"%s\"" % h for h in hashes]),
        ))

    return _HEADER + "".join(blocks)

def module_lock_document(mirror_hashes, declared, default_registry):
    """The lock document for a module tree: the three passes above, in order.

    Args:
      mirror_hashes: the tf toolchain's flat hash table.
      declared: the `providers` dicts of the module and its dependencies.
      default_registry: registry host an unqualified source resolves against.

    Returns:
      The document, or "" when the mirror is empty.
    """
    by_address = parse_mirror_hashes(mirror_hashes)
    return render_lock_document(
        by_address,
        select_lock_versions(by_address, declared_constraints(declared, default_registry)),
    )
