"""Renders a module's .terraform.lock.hcl from the mirror's recorded provider hashes."""

load(":provider_mirror.bzl", "provider_source_parts")
load(":semver.bzl", "select_matching_version")

_HEADER = """# Generated by rules_tf from the provider mirror. Do not edit.
#
# The zh: hashes below are the package sha256s the module extension resolved
# when the mirror was built, one per platform; the h1: hashes cover the same
# packages extracted, as terraform installs them. The mirror is the only place
# these providers can be installed from, so this records what terraform is about
# to link rather than constraining what it may choose.
"""

_PROVIDER_BLOCK = """
provider "{address}" {{
  version = "{version}"
  hashes = [
{hashes}
  ]
}}
"""

def parse_mirror_hashes(mirror_hashes):
    """Groups a provider mirror's hashes by address and version.

    Args:
      mirror_hashes: a dict keyed "address@version", each value a
        comma-joined string of package hashes.

    Returns:
      A dict of address to {version: [hashes]}.
    """
    by_address = {}
    for key, joined in mirror_hashes.items():
        address, _, version = key.rpartition("@")
        by_address.setdefault(address, {})[version] = [h for h in joined.split(",") if h]

    return by_address

def declared_constraints(declared, default_registry):
    """Collects the version constraints a module's parsed configs declare.

    Every declared provider gets an entry, even with no version constraint,
    so callers can tell "declared but unconstrained" from "never declared".

    Args:
      declared: the `providers` dicts of a module and its dependencies.
      default_registry: registry host an unqualified source resolves against.

    Returns:
      A dict of provider address to the list of version constraints declared for it.
    """
    constraints = {}
    for providers in declared:
        for config in providers.values():
            host, namespace, provider_type = provider_source_parts(
                config["source"],
                default_registry,
            )
            address = "%s/%s/%s" % (host, namespace, provider_type)
            specs = constraints.setdefault(address, [])

            spec = config.get("version")
            if spec and spec not in specs:
                specs.append(spec)

    return constraints

def _satisfying_version(versions, specs):
    """Picks the mirrored version satisfying every spec.

    Falls back to an exact match against a pinned spec ("= x" or bare "x")
    when select_matching_version rejects it, e.g. a prerelease pin.

    Returns:
      The satisfying version, or "" if none of the mirrored versions qualify.
    """

    version = select_matching_version(versions, ", ".join(specs))
    if version:
        return version

    pins = [
        spec.strip()[1:].strip() if spec.strip().startswith("=") else spec.strip()
        for spec in specs
    ]
    for candidate in versions:
        if candidate in pins:
            return candidate

    return ""

def select_lock_versions(by_address, constraints):
    """Chooses one mirrored version per declared provider address.

    An address mirrored but never declared is skipped. A declared address
    with no version constraint is selected only if the mirror holds exactly
    one version for it. A declared address with no mirrored version
    satisfying its constraints is silently omitted, not an error.

    Args:
      by_address: mirror contents, as `parse_mirror_hashes` returns them.
      constraints: declared providers, as `declared_constraints` returns them.

    Returns:
      A dict of provider address to the selected version.
    """
    selected = {}
    for address, versions in by_address.items():
        specs = constraints.get(address)
        if specs == None:
            continue

        if not specs:
            if len(versions) == 1:
                selected[address] = versions.keys()[0]
            continue

        version = _satisfying_version(versions.keys(), specs)
        if version:
            selected[address] = version

    return selected

def render_lock_document(by_address, selected):
    """Renders the lock file text for the selected provider versions.

    Args:
      by_address: mirror contents, as `parse_mirror_hashes` returns them.
      selected: one version per address, as `select_lock_versions` returns them.

    Returns:
      The lock file contents, or "" if no versions were selected.
    """
    if not selected:
        return ""

    blocks = []
    for address in sorted(selected):
        version = selected[address]
        hashes = sorted(by_address[address][version])
        blocks.append(_PROVIDER_BLOCK.format(
            address = address,
            version = version,
            hashes = ",\n".join(["    \"%s\"" % h for h in hashes]),
        ))

    return _HEADER + "".join(blocks)

def module_lock_document(mirror_hashes, declared, default_registry):
    """Builds the .terraform.lock.hcl contents for a module, or "" if none is needed.

    Args:
      mirror_hashes: see parse_mirror_hashes.
      declared: see declared_constraints.
      default_registry: see declared_constraints.
    """
    by_address = parse_mirror_hashes(mirror_hashes)
    return render_lock_document(
        by_address,
        select_lock_versions(by_address, declared_constraints(declared, default_registry)),
    )
